name: todo_app_getx
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  connectivity_plus: ^2.3.6+1

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  url_launcher: ^6.1.5
  path_provider: ^2.0.11
  share_plus: ^4.0.10+1
  shimmer: ^2.0.0
  hive: ^2.2.3
  flutter_html: ^2.2.1
  vibration: ^1.7.5
  intl: ^0.17.0
  dio: ^4.0.6
  dotted_border: ^2.0.0
  flutter_local_notifications: ^9.7.0
  flutter_time_picker_spinner: ^2.0.0
  lint: ^1.10.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.15
  syncfusion_flutter_datepicker: ^20.2.40
  timeline_tile: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/texts/Poppins-Black.ttf
        - asset: assets/fonts/texts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/texts/Poppins-Bold.ttf
        - asset: assets/fonts/texts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/texts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/texts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/texts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/texts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/texts/Poppins-Italic.ttf
        - asset: assets/fonts/texts/Poppins-Light.ttf
        - asset: assets/fonts/texts/Poppins-LightItalic.ttf
        - asset: assets/fonts/texts/Poppins-Medium.ttf
        - asset: assets/fonts/texts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/texts/Poppins-Regular.ttf
        - asset: assets/fonts/texts/Poppins-SemiBold.ttf
        - asset: assets/fonts/texts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/texts/Poppins-Thin.ttf
        - asset: assets/fonts/texts/Poppins-ThinItalic.ttf
